import { constructUrl } from ".";

const {
	REACT_APP_BASE_URL,
	REACT_APP_VIDEO_URL_1,
	REACT_APP_VTT_URL_1,
	REACT_APP_IMAGE_SPRITE_URL_1,
	REACT_APP_IMAGE_SPRITE_KEY_1,
	REACT_APP_CHAPTERS_URL_1,

	REACT_APP_VIDEO_URL_2,
	REACT_APP_VTT_URL_2,
	REACT_APP_IMAGE_SPRITE_URL_2,
	REACT_APP_IMAGE_SPRITE_KEY_2,
	REACT_APP_CHAPTERS_URL_2,
} = process.env;

const VIDEO_SRC_1 = constructUrl([REACT_APP_BASE_URL, REACT_APP_VIDEO_URL_1]);
const VTT_SRC_1 = constructUrl([REACT_APP_BASE_URL, REACT_APP_VTT_URL_1]);
const IMAGE_SPRITE_URL_1 = constructUrl([
	REACT_APP_BASE_URL,
	REACT_APP_IMAGE_SPRITE_URL_1,
]);
const CHAPTERS_VTT_SRC_1 = constructUrl([
	REACT_APP_BASE_URL,
	REACT_APP_CHAPTERS_URL_1,
]);

const VIDEO_SRC_2 = constructUrl([REACT_APP_BASE_URL, REACT_APP_VIDEO_URL_2]);
const VTT_SRC_2 = constructUrl([REACT_APP_BASE_URL, REACT_APP_VTT_URL_2]);
const IMAGE_SPRITE_URL_2 = constructUrl([
	REACT_APP_BASE_URL,
	REACT_APP_IMAGE_SPRITE_URL_2,
]);
const CHAPTERS_VTT_SRC_2 = constructUrl([
	REACT_APP_BASE_URL,
	REACT_APP_CHAPTERS_URL_2,
]);

export const VIDEO_INFO_1 = {
	src: VIDEO_SRC_1,
	vtt: VTT_SRC_1,
	sprite: IMAGE_SPRITE_URL_1,
	spriteKey: REACT_APP_IMAGE_SPRITE_KEY_1,
	chapters: CHAPTERS_VTT_SRC_1,
};

export const VIDEO_INFO_2 = {
	src: VIDEO_SRC_2,
	vtt: VTT_SRC_2,
	sprite: IMAGE_SPRITE_URL_2,
	spriteKey: REACT_APP_IMAGE_SPRITE_KEY_2,
	chapters: CHAPTERS_VTT_SRC_2,
};
