// actions
export const PLAY_PAUSE = 'PLAY_PAUSE';
export const ON_MUTE = 'ON_MUTE';
export const VOLUME_CHANGE = 'VOLUME_CHANGE';
export const HAS_VIDEO_LOADED = 'HAS_VIDEO_LOADED';
export const UPDATE_VIDEO_CURRENT_TIME = 'UPDATE_VIDEO_CURRENT_TIME';
export const UPDATE_HOVERED_DURATION = 'UPDATE_HOVERED_DURATION';
export const UPDATE_HOVERED_THUMBNAIL_URL = 'UPDATE_HOVERED_THUMBNAIL_URL';
export const UPDATE_SEEKING = 'UPDATE_SEEKING';
